### ISSUE TITLE
g.NEEDaccess CMake error

### ISSUE THREAD

**Issue by JohnAtl** [labstreaminglayer/App-g.Tec#11]
Hello @cboulay ,    
I have Visual Studio 2019 and Qt 5.12.11 installed. After configuring x64-Debug, gNEEDaccess*, Qt5*, and LSL_DIR, are pointed to their correct folders. In trying to compile g.NEEDaccess, I'm stumped by the following error.
```
CMake Error at C:/Users/johnj/source/liblsl-1.15-Win_amd64/lib/cmake/LSL/LSLCMake.cmake:259 (get_target_property):   
get_target_property() called with non-existent target "Qt::qmake".    
C:/Users/johnj/source/liblsl-1.15-Win_amd64/lib/cmake/LSL/LSLCMake.cmake | 259 |  
```

I'm happy to post more detail (I don't know what I don't know at this point), and would appreciate any help.

**Comment by cboulay** [comment]
I'll try to reproduce the build problem on my end. In the meantime, did you try the build on the release page?
https://github.com/labstreaminglayer/App-g.Tec/releases

**Comment by JohnAtl** [comment]
Gah! Completely missed that. 
Thanks!

**Comment by cboulay** [comment]
I've identified the error. Basically, more recent versions of Qt + Cmake allow `Qt::module` whereas versions prior to Qt5.15 required `Qt5::module`. That particular line in the LSLCMake.cmake file has been updated to use the newer syntax, effectively making it no longer compatible with Qt5.12 or earlier, but it is compatible with Qt6. You can modify it from `Qt::` to `Qt5::` and you can use it in Qt5 projects (but not Qt6).

I'm not going to fix this because identifying the correct prefix is a little more work than I'm willing to do right now given that we're going to change our LSLCMake distribution in the near future anyway.

FYI, I rebuilt gNEEDaccess using Qt5.15 and liblsl 1.15 and added it to the same release; it's the zip with `0.15` in its filename.
